#!/bin/bash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

source comparelib.sh

is=$(sanitise "$@")

while read line; do
	if echo $line | grep -q '^$'; then
		continue
	fi

	echo -n $line...
	
	if echo $line | grep -q '^-'; then
		nostart=$(echo $line | sed 's/^-\([[:alnum:]_\.\-]\+\)/[[:blank:]]\1[[:blank:]]/')
		if echo " $is " | grep -q -e "$nostart"; then
			err_ex "$line should not have been started but is: $is"
		fi
	elif echo $line | grep -q '^+'; then
		nostart=$(echo $line | sed 's/^+\([[:alnum:]_\.\-]\+\)/[[:blank:]]\1[[:blank:]]/')
		if ! echo " $is " | grep -q -e "$nostart"; then
			err_ex "$line should have been started but is not: $is"
		fi
	else
		rex=$(echo $line | sed -e 's/[[:blank:]]*\([[:alnum:]_\.\-]\+\)[[:blank:]]\+before[[:blank:]]\+\([[:alnum:]_\.\-]\+\)[[:blank:]]*/[[:blank:]]\\+\1[[:blank:]]\\+\\(.*[[:blank:]]\\+\\)\*\2/')

		echo " $is " | grep -q -e "$rex" || err_ex "$is DOES NOT MATCH $rex"
	fi
	echo "ok"
done
