#!/bin/bash
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

source comparelib.sh

for n in ./tests/0[1-5]; do
	echo -e "\n\ntest $n:"
	for l in 0 1 2 3 4 5 6 S; do
		echo -e "\nrunlevel $l:"
		if [ -f $n/expected_$l ]; then
			./compare_result `cat $n/expected_$l` XXXX $(./bootage $l test $n)
		fi

		if [ -f $n/rel_expected_$l ]; then
			cat $n/rel_expected_$l | ./compare_rel $(./bootage $l test $n)
		fi
	done
done

# yeah, i agree there should be a nicer test suite...
# individual tests:

# segfault
./bootage 5 test tests/06/ && err_ex "test 6 should have failed because of circular deps"

echo done.
