# $Id: Makefile.nt,v 1.17 2008-12-03 18:09:09 doligez Exp $

OTHERSLIB=-I $(OTHERS)/win32unix -I $(OTHERS)/str -I $(OTHERS)/systhreads

CCFLAGS=-I../../../byterun $(TK_DEFS)

include ../support/Makefile.common

ifeq ($(CCOMPTYPE),cc)
WINDOWS_APP=-ccopt "-link -Wl,--subsystem,windows"
else
WINDOWS_APP=-ccopt "-link /subsystem:windows"
endif

XTRAOBJ=winmain.$(O)
XTRALIBS=threads.cma -custom $(WINDOWS_APP)

include Makefile.shared

dummy.mli:
	cp dummyWin.mli dummy.mli
